name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
          args: >
            --timeout=1m
            --out-format=colored-line-number
            ./...

  test:
    name: go test (race + coverage)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.23.5"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run tests
        run: |
          go test -shuffle=on -race -covermode=atomic -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | tail -n1

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.go }}
          path: coverage.out
          if-no-files-found: error
