name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    if: ${{ hashFiles('go.mod') != '' && hashFiles('**/*.go') != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
          args: >
            --timeout=3m
            --out-format=colored-line-number
            ./...

  test:
    name: go test (race + coverage)
    runs-on: ubuntu-latest
    if: ${{ hashFiles('go.mod') != '' && hashFiles('**/*.go') != '' }}
    strategy:
      fail-fast: false
      matrix:
        go: ["1.22", "1.23.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run tests (race + coverage)
        id: gotest
        run: |
          go test -shuffle=on -race -covermode=atomic -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | tail -n1

      - name: Upload coverage artifact
        if: ${{ success() && steps.gotest.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.go }}
          path: coverage.out
          if-no-files-found: error

  noop:
    name: repo bootstrap
    runs-on: ubuntu-latest
    if: ${{ !(hashFiles('go.mod') != '' && hashFiles('**/*.go') != '') }}
    steps:
      - run: echo "No Go code yet — skipping lint & tests."
